console.log('Hola mundo, mi nombre es: Yezid Blanco')
console.log('Ejercicio: Cajero')
console.log('Entrada: Introduces tu tarjeta y selecciona la cantidad de dinero que deseas retirar')
console.log('Proceso: El cajero verifica tu información y realiza la transacción en tu cuenta bancaria')
console.log('Salida: Recibes el dinero solicitado y un recibo')
console.log('Ejercicio: Calculadora')
console.log('Entrada: Introducir primer numero, indicar operacion, segundo numero')
console.log('Proceso: Se realiza la operacion entre los dos numeros')
console.log('Salida: Entrega el resultado en pantalla')
console.log('Ejercicio: Horno microondas')
console.log('Entrada: Abrir puerta, introducir comida, cerrar puerta, digitar tiempo a calentar y seleccionar calentar')
console.log('Proceso: Se calientan los alimentos durante el tiempo seleccionado, terminado genera alarma y listo para retirar')
console.log('Salida: Se abre la puerta y se retira la comida caliente')
console.log('Ejercicio: Lavadora')
console.log('Entrada: Se abre la puerta, se introduce la ropa sucia, se añade detergente, se selecciona un ciclo de ladado, se ceirra la puerta')
console.log('Proceso: Realiza el proceso de llenado de agua, enjuagado y realiza el ciclo de labado, terminado se genera alarma')
console.log('Salida: Se abre la puerta, se procede a retirar la ropa limpia y se cierra la puerta')